/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package railway;

import javax.swing.JOptionPane;

/**
 *
 * @author cletu
 */
public class bookfinal extends javax.swing.JFrame {

    /**
     * Creates new form bookfinal
     */
    public bookfinal() {
        initComponents();
        train_name.setText(global.bkdetails.slcttrain.name+" ("+global.bkdetails.slcttrain.number+")");
        src_station.setText(global.bkdetails.srcstation.name+" ("+global.bkdetails.srcstation.code+")");
        dest_station.setText(global.bkdetails.deststation.name+" ("+global.bkdetails.deststation.code+")");
        departure.setText(global.bkdetails.arrtime+"hrs");
        date.setText(global.bkdetails.traveldate.dt);
        psgr_name.setText(global.bkdetails.psgrname);
        psgr_age.setText(global.bkdetails.psgrage+"");
        coach_type.setText(global.bkdetails.coachtype);
        quota.setText(global.bkdetails.quota);
        ticket_fare.setText("Rs. "+global.bkdetails.price);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        train_name = new javax.swing.JLabel();
        label_srcstation = new javax.swing.JLabel();
        label_deststation = new javax.swing.JLabel();
        label_departure = new javax.swing.JLabel();
        label_date = new javax.swing.JLabel();
        label_psgrname = new javax.swing.JLabel();
        label_psgrage = new javax.swing.JLabel();
        label_coachtype = new javax.swing.JLabel();
        label_quota = new javax.swing.JLabel();
        label_fare = new javax.swing.JLabel();
        src_station = new javax.swing.JLabel();
        dest_station = new javax.swing.JLabel();
        departure = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        psgr_name = new javax.swing.JLabel();
        psgr_age = new javax.swing.JLabel();
        coach_type = new javax.swing.JLabel();
        quota = new javax.swing.JLabel();
        ticket_fare = new javax.swing.JLabel();
        button_booktkt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("RAIL TRANSIT");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        train_name.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N

        label_srcstation.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_srcstation.setText("Source Station: ");

        label_deststation.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_deststation.setText("Destination Station: ");

        label_departure.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_departure.setText("Departure: ");

        label_date.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_date.setText("Date: ");

        label_psgrname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_psgrname.setText("Name of Passenger: ");

        label_psgrage.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_psgrage.setText("Age: ");

        label_coachtype.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_coachtype.setText("Class: ");

        label_quota.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_quota.setText("Quota: ");

        label_fare.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_fare.setText("Fare: ");

        src_station.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        dest_station.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        departure.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        date.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        psgr_name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        psgr_age.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        coach_type.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        quota.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        ticket_fare.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        button_booktkt.setText("Book Ticket");
        button_booktkt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_booktktActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(train_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_srcstation)
                            .addComponent(label_deststation)
                            .addComponent(label_departure)
                            .addComponent(label_date)
                            .addComponent(label_psgrname)
                            .addComponent(label_psgrage)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(label_quota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(label_coachtype, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(label_fare))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(src_station, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dest_station, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(departure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(psgr_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(psgr_age, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(coach_type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ticket_fare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(button_booktkt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(train_name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_srcstation)
                            .addComponent(src_station))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_deststation)
                            .addComponent(dest_station))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_departure))
                    .addComponent(departure))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_date)
                    .addComponent(date))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_psgrname)
                    .addComponent(psgr_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_psgrage)
                    .addComponent(psgr_age))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_coachtype)
                    .addComponent(coach_type))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_quota)
                    .addComponent(quota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_fare)
                    .addComponent(ticket_fare))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(button_booktkt)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 666, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_booktktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_booktktActionPerformed
        String status;
        if(global.bkdetails.slcttrain.seatavailable(global.bkdetails.coachtype, global.bkdetails.quota)>0) {
            status="CNF";
        }
        else {
            status="WL";
        }
        int flag=0;
        int flag2=0;
        String bookedquota = null;
        switch (global.bkdetails.coachtype) {
            case "3AC":
                switch (global.bkdetails.quota) {
                    case "women":
                        for(int i=0; i<3; i++) {
                            if(!global.bkdetails.slcttrain.threeac.women[i].occupied) {
                                global.bkdetails.seatnm=global.bkdetails.slcttrain.threeac.women[i];
                                global.bkdetails.slcttrain.threeac.women[i].occupied=true;
                                bookedquota="Women";
                                flag=1;
                                break;
                            }
                        }
                        if(flag==0) {
                            for(int i=0; i<9; i++) {
                                if(!global.bkdetails.slcttrain.threeac.general[i].occupied) {
                                    global.bkdetails.seatnm=global.bkdetails.slcttrain.threeac.general[i];
                                    global.bkdetails.slcttrain.threeac.general[i].occupied=true;
                                    bookedquota="General";
                                    flag2=1;
                                    break;
                                }
                            }
                            if(flag2==0) {
                                bookedquota="Women";
                            }
                        }   
                        break;
                    case "srcitizen":
                        for(int i=0; i<3; i++) {
                            if(!global.bkdetails.slcttrain.threeac.srcitizen[i].occupied) {
                                global.bkdetails.seatnm=global.bkdetails.slcttrain.threeac.srcitizen[i];
                                global.bkdetails.slcttrain.threeac.srcitizen[i].occupied=true;
                                bookedquota="Senior Citizen";
                                flag=1;
                                break;
                            }
                        }   
                        if(flag==0) {
                            for(int i=0; i<9; i++) {
                                if(!global.bkdetails.slcttrain.threeac.general[i].occupied) {
                                    global.bkdetails.seatnm=global.bkdetails.slcttrain.threeac.general[i];
                                    global.bkdetails.slcttrain.threeac.general[i].occupied=true;
                                    bookedquota="General";
                                    flag2=1;
                                    break;
                                }
                            }
                            if(flag2==0) {
                                bookedquota="Senior Citizen";
                            }
                        }   
                        break;
                    default:
                        for(int i=0; i<9; i++) {
                            if(!global.bkdetails.slcttrain.threeac.general[i].occupied) {
                                global.bkdetails.seatnm=global.bkdetails.slcttrain.threeac.general[i];
                                global.bkdetails.slcttrain.threeac.general[i].occupied=true;
                                bookedquota="General";
                                flag2=1;
                                break;
                            }
                        } 
                        if(flag2==0) {
                            bookedquota="General";
                        }
                        break;
                }   
                break;
            case "SL":
                switch (global.bkdetails.quota) {
                    case "women":
                        for(int i=0; i<3; i++) {
                            if(!global.bkdetails.slcttrain.sleeper.women[i].occupied) {
                                global.bkdetails.seatnm=global.bkdetails.slcttrain.sleeper.women[i];
                                global.bkdetails.slcttrain.sleeper.women[i].occupied=true;
                                bookedquota="Women";
                                flag=1;
                                break;
                            }
                        }
                        if(flag==0) {
                            for(int i=0; i<9; i++) {
                                if(!global.bkdetails.slcttrain.sleeper.general[i].occupied) {
                                    global.bkdetails.seatnm=global.bkdetails.slcttrain.sleeper.general[i];
                                    global.bkdetails.slcttrain.sleeper.general[i].occupied=true;
                                    bookedquota="General";
                                    flag2=1;
                                    break;
                                }
                            }
                            if(flag2==0) {
                                bookedquota="Women";
                            }
                        }   
                        break;
                    case "srcitizen":
                        for(int i=0; i<3; i++) {
                            if(!global.bkdetails.slcttrain.sleeper.srcitizen[i].occupied) {
                                global.bkdetails.seatnm=global.bkdetails.slcttrain.sleeper.srcitizen[i];
                                global.bkdetails.slcttrain.sleeper.srcitizen[i].occupied=true;
                                bookedquota="Senior Citizen";
                                flag=1;
                                break;
                            }
                        }
                        if(flag==0) {
                            for(int i=0; i<9; i++) {
                                if(!global.bkdetails.slcttrain.sleeper.general[i].occupied) {
                                    global.bkdetails.seatnm=global.bkdetails.slcttrain.sleeper.general[i];
                                    global.bkdetails.slcttrain.sleeper.general[i].occupied=true;
                                    bookedquota="General";
                                    flag2=1;
                                    break;
                                }
                            }
                            if(flag2==0) {
                                bookedquota="Senior Citizen";
                            }
                        }   
                        break;
                    default:
                        for(int i=0; i<9; i++) {
                            if(!global.bkdetails.slcttrain.sleeper.general[i].occupied) {
                                global.bkdetails.seatnm=global.bkdetails.slcttrain.sleeper.general[i];
                                global.bkdetails.slcttrain.sleeper.general[i].occupied=true;
                                bookedquota="General";
                                flag2=1;
                                break;
                            }
                        }   
                        if(flag2==0) {
                                bookedquota="General";
                        }
                        break;
                }   break;
            default:
                switch (global.bkdetails.quota) {
                    case "women":
                        for(int i=0; i<3; i++) {
                            if(!global.bkdetails.slcttrain.chaircar.women[i].occupied) {
                                global.bkdetails.seatnm=global.bkdetails.slcttrain.chaircar.women[i];
                                global.bkdetails.slcttrain.chaircar.women[i].occupied=true;
                                bookedquota="Women";
                                flag=1;
                                break;
                            }
                        }   
                        if(flag==0) {
                            for(int i=0; i<9; i++) {
                                if(!global.bkdetails.slcttrain.chaircar.general[i].occupied) {
                                    global.bkdetails.seatnm=global.bkdetails.slcttrain.chaircar.general[i];
                                    global.bkdetails.slcttrain.chaircar.general[i].occupied=true;
                                    bookedquota="General";
                                    flag2=1;
                                    break;
                                }
                            }
                            if(flag2==0) {
                                bookedquota="Women";
                            }
                        }   
                        break;
                    case "srcitizen":
                        for(int i=0; i<3; i++) {
                            if(!global.bkdetails.slcttrain.chaircar.srcitizen[i].occupied) {
                                global.bkdetails.seatnm=global.bkdetails.slcttrain.chaircar.srcitizen[i];
                                global.bkdetails.slcttrain.chaircar.srcitizen[i].occupied=true;
                                bookedquota="Senior Citizen";
                                flag=1;
                                break;
                            }
                        }   
                        if(flag==0) {
                            for(int i=0; i<9; i++) {
                                if(!global.bkdetails.slcttrain.chaircar.general[i].occupied) {
                                    global.bkdetails.seatnm=global.bkdetails.slcttrain.chaircar.general[i];
                                    global.bkdetails.slcttrain.chaircar.general[i].occupied=true;
                                    bookedquota="General";
                                    flag2=1;
                                    break;
                                }
                            }
                            if(flag2==0) {
                                bookedquota="Senior Citizen";
                            }
                        }   
                        break;
                    default:
                        for(int i=0; i<9; i++) {
                            if(!global.bkdetails.slcttrain.threeac.general[i].occupied) {
                                global.bkdetails.seatnm=global.bkdetails.slcttrain.chaircar.general[i];
                                global.bkdetails.slcttrain.threeac.general[i].occupied=true;
                                bookedquota="General";
                                flag2=1;
                                break;
                            }
                        }
                        if(flag2==0) {
                            bookedquota="General";
                        }
                        break;
                }   break;
        }
//        String status;
//        if(global.bkdetails.slcttrain.seatavailable(global.bkdetails.coachtype, global.bkdetails.quota)>0) {
//            status="CNF";
//        }
//        else {
//            status="WL";
//        }
        ticket bktkt=new ticket(global.curpnr++, global.bkdetails.srcstation, global.bkdetails.deststation, global.bkdetails.slcttrain.number, global.bkdetails.arrtime, global.bkdetails.psgrname, global.bkdetails.slcttrain.name+" ("+global.bkdetails.slcttrain.number+")", global.bkdetails.traveldate, global.bkdetails.psgrage, bookedquota, global.bkdetails.coachtype, global.bkdetails.seatnm.number, status, global.bkdetails.price);
        global.tktlink.insertlast(bktkt);
        JOptionPane.showMessageDialog(this, "Ticket Booked Successfully!");
        this.hide();
        global.home.setVisible(true);
    }//GEN-LAST:event_button_booktktActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookfinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookfinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookfinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookfinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookfinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_booktkt;
    private javax.swing.JLabel coach_type;
    private javax.swing.JLabel date;
    private javax.swing.JLabel departure;
    private javax.swing.JLabel dest_station;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_coachtype;
    private javax.swing.JLabel label_date;
    private javax.swing.JLabel label_departure;
    private javax.swing.JLabel label_deststation;
    private javax.swing.JLabel label_fare;
    private javax.swing.JLabel label_psgrage;
    private javax.swing.JLabel label_psgrname;
    private javax.swing.JLabel label_quota;
    private javax.swing.JLabel label_srcstation;
    private javax.swing.JLabel psgr_age;
    private javax.swing.JLabel psgr_name;
    private javax.swing.JLabel quota;
    private javax.swing.JLabel src_station;
    private javax.swing.JLabel ticket_fare;
    private javax.swing.JLabel train_name;
    // End of variables declaration//GEN-END:variables
}
