package railway;

import javax.swing.JOptionPane;

public class canceltkt extends javax.swing.JFrame {

    /**
     * Creates new form canceltkt
     */
    public canceltkt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basepanel = new javax.swing.JPanel();
        rail_transit = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        in_pnrno = new javax.swing.JTextField();
        pnr_number = new javax.swing.JLabel();
        button_cancel = new javax.swing.JButton();
        button_logout = new javax.swing.JButton();
        button_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        basepanel.setBackground(new java.awt.Color(255, 204, 153));

        rail_transit.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        rail_transit.setText("RAIL TRANSIT");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        in_pnrno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_pnrnoActionPerformed(evt);
            }
        });

        pnr_number.setText("Enter PNR Number: ");

        button_cancel.setText("Cancel Ticket");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(pnr_number)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_pnrno, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_cancel)
                .addGap(350, 350, 350))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(in_pnrno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnr_number))
                .addGap(65, 65, 65)
                .addComponent(button_cancel)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        button_logout.setText("Log Out");
        button_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_logoutActionPerformed(evt);
            }
        });

        button_back.setText("Back");
        button_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout basepanelLayout = new javax.swing.GroupLayout(basepanel);
        basepanel.setLayout(basepanelLayout);
        basepanelLayout.setHorizontalGroup(
            basepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basepanelLayout.createSequentialGroup()
                .addComponent(rail_transit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 510, Short.MAX_VALUE)
                .addComponent(button_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_logout)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        basepanelLayout.setVerticalGroup(
            basepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rail_transit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_logoutActionPerformed
        this.hide();
        global.lgn.setVisible(true);
    }//GEN-LAST:event_button_logoutActionPerformed

    private void button_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_backActionPerformed
        this.hide();
        global.home.setVisible(true);
    }//GEN-LAST:event_button_backActionPerformed

    private void in_pnrnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_pnrnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_pnrnoActionPerformed

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
        ticket cur=global.tktlink.first;
        int flag=0;
        while(cur!=null) {
            if(cur.pnr==Integer.parseInt(in_pnrno.getText())) {
                date deldate=global.dtlink.first;
                while(deldate!=null) {
                    if(deldate==cur.date) {
                        break;
                    }
                    deldate=deldate.next;
                }
                train deltrain=deldate.trnlink.first;
                while(deltrain!=null) {
                    if(deltrain.number==cur.train_no) {
                        String delcoach=cur.coachtype;
                        String delquota=cur.quota;
                        ticket curwait=global.tktlink.first;
                        int flagfound=0;
                        while(curwait!=null) {
                            if(curwait.status.equals("WL")&&curwait.quota.equals(delquota)) {
                                curwait.status="CNF";
                                flagfound=1;
                                break;
                            }
                            curwait=curwait.next;
                        }
                        if(flagfound==0) {
                            switch (delcoach) {
                                case "SL":
                                    switch (delquota) {
                                        case "Women":
                                            for(int i=0; i<3; i++) {
                                                if(cur.seatno==deltrain.sleeper.women[i].number) {
                                                    deltrain.sleeper.women[i].occupied=false;
                                                    break;
                                                }
                                            }   break;
                                        case "Senior Citizen":
                                            for(int i=0; i<3; i++) {
                                                if(cur.seatno==deltrain.sleeper.srcitizen[i].number) {
                                                    deltrain.sleeper.srcitizen[i].occupied=false;
                                                    break;
                                                }
                                            }   break;
                                        default:
                                            for(int i=0; i<9; i++) {
                                                if(cur.seatno==deltrain.sleeper.general[i].number) {
                                                    deltrain.sleeper.general[i].occupied=false;
                                                    break;
                                                }
                                            }   break;
                                    }   break;
                                case "3AC":
                                    switch (delquota) {
                                        case "Women":
                                            for(int i=0; i<3; i++) {
                                                if(cur.seatno==deltrain.threeac.women[i].number) {
                                                    deltrain.threeac.women[i].occupied=false;
                                                    break;
                                                }
                                            }   break;
                                        case "Senior Citizen":
                                            for(int i=0; i<3; i++) {
                                                if(cur.seatno==deltrain.threeac.srcitizen[i].number) {
                                                    deltrain.threeac.srcitizen[i].occupied=false;
                                                    break;
                                                }
                                            }   break;
                                        default:
                                            for(int i=0; i<9; i++) {
                                                if(cur.seatno==deltrain.threeac.general[i].number) {
                                                    deltrain.threeac.general[i].occupied=false;
                                                    break;
                                                }
                                            }   break;
                                    }   break;
                                default:
                                    switch (delquota) {
                                        case "Women":
                                            for(int i=0; i<3; i++) {
                                                if(cur.seatno==deltrain.chaircar.women[i].number) {
                                                    deltrain.chaircar.women[i].occupied=false;
                                                    break;
                                                }
                                            }   break;
                                        case "Senior Citizen":
                                            for(int i=0; i<3; i++) {
                                                if(cur.seatno==deltrain.chaircar.srcitizen[i].number) {
                                                    deltrain.chaircar.srcitizen[i].occupied=false;
                                                    break;
                                                }
                                            }   break;
                                        default:
                                            for(int i=0; i<9; i++) {
                                                if(cur.seatno==deltrain.chaircar.general[i].number) {
                                                    deltrain.chaircar.general[i].occupied=false;
                                                    break;
                                                }
                                            }   break;
                                    }   break;
                            }
                        }
                        break;
                    }
                    deltrain=deltrain.next;
                }
                if(cur==global.tktlink.first) {
                    global.tktlink.first=global.tktlink.first.next;
                    flag=1;
                    break;
                }
                else if(cur==global.tktlink.last) {
                    global.tktlink.last=global.tktlink.last.prev;
                    global.tktlink.last.next=null;
                    flag=1;
                    break;
                }
                else {
                    cur.prev.next=cur.next;
                    cur.next.prev=cur.prev;
                    flag=1;
                    break;
                }
            }
            cur=cur.next;
        }
        if(flag==0) {
            JOptionPane.showMessageDialog(this, "Invalid PNR Number!");
        }
        else {
            JOptionPane.showMessageDialog(this, "Ticket Cancelled Successfully");
            this.hide();
            global.home.setVisible(true);
        }
    }//GEN-LAST:event_button_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(canceltkt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(canceltkt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(canceltkt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(canceltkt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new canceltkt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basepanel;
    private javax.swing.JButton button_back;
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_logout;
    private javax.swing.JTextField in_pnrno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pnr_number;
    private javax.swing.JLabel rail_transit;
    // End of variables declaration//GEN-END:variables
}