package railway;

import javax.swing.table.DefaultTableModel;

public class showtrains extends javax.swing.JFrame {

    /**
     * Creates new form showtrains
     */
    public showtrains() {
        initComponents();
        train cur=global.bkdetails.traveldate.trnlink.first;
        DefaultTableModel model=(DefaultTableModel)table_trains.getModel();
        model.setRowCount(0);
        while(cur!=null) {
            if(cur.priority<=global.bkdetails.srcstation.priority&&cur.priority<=global.bkdetails.deststation.priority&&cur.direction==global.bkdetails.direction) {
                int trndist;
                if(cur.direction=='n') {
                    trndist=global.bkdetails.srcstation.src_distance-cur.start.src_distance;
                }
                else {
                    trndist=(global.bkdetails.srcstation.src_distance-cur.start.src_distance)*(-1);
                }
                global.bkdetails.arrtime=cur.starttime+(trndist/60)*100+(trndist%60);
                if(global.bkdetails.direction=='n') {
                    global.bkdetails.distance=global.bkdetails.deststation.src_distance-global.bkdetails.srcstation.src_distance;
                }
                else {
                    global.bkdetails.distance=global.bkdetails.srcstation.src_distance-global.bkdetails.deststation.src_distance;
                }
                int seata=0;
                String ctype=global.bkdetails.coachtype;
                switch (ctype) {
                    case "SL":
                        seata=cur.seatavailable(cur.sleeper.type, global.bkdetails.quota);
                        global.bkdetails.price=100;
                        if(global.bkdetails.distance>5) {
                            global.bkdetails.price+=(global.bkdetails.distance-5)*5;
                        }
                        break;
                    case "3AC":
                        seata=cur.seatavailable(cur.threeac.type, global.bkdetails.quota);
                        global.bkdetails.price=500;
                        if(global.bkdetails.distance>10) {
                            global.bkdetails.price+=(global.bkdetails.distance-10)*15;
                        }
                        break;
                    case "CC":
                        seata=cur.seatavailable(cur.chaircar.type, global.bkdetails.quota);
                        global.bkdetails.price=250;
                        if(global.bkdetails.distance>8) {
                            global.bkdetails.price+=(global.bkdetails.distance-8)*10;
                        }
                        break;
                    default:
                        break;
                }
                int trainpr=cur.priority;
                switch(trainpr) {
                    case 2:
                        global.bkdetails.price+=10;
                        break;
                    case 3:
                        global.bkdetails.price+=25;
                        break;
                    default:
                        break;
                }
                model.addRow(new Object[] {
                cur.number, cur.name, global.bkdetails.arrtime, seata, global.bkdetails.price});
            }
            cur=cur.next;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basepanel = new javax.swing.JPanel();
        rail_transit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_trains = new javax.swing.JTable();
        button_logout = new javax.swing.JButton();
        button_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        basepanel.setBackground(new java.awt.Color(255, 204, 153));

        rail_transit.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        rail_transit.setText("RAIL TRANSIT");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        table_trains.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Number", "Name", "Time (hrs)", "Seat Available", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_trains.getTableHeader().setReorderingAllowed(false);
        table_trains.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_trainsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_trains);
        if (table_trains.getColumnModel().getColumnCount() > 0) {
            table_trains.getColumnModel().getColumn(0).setPreferredWidth(5);
            table_trains.getColumnModel().getColumn(1).setPreferredWidth(100);
            table_trains.getColumnModel().getColumn(2).setPreferredWidth(5);
            table_trains.getColumnModel().getColumn(3).setPreferredWidth(5);
            table_trains.getColumnModel().getColumn(4).setPreferredWidth(5);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addContainerGap())
        );

        button_logout.setText("Log Out");
        button_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_logoutActionPerformed(evt);
            }
        });

        button_back.setText("Back");
        button_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout basepanelLayout = new javax.swing.GroupLayout(basepanel);
        basepanel.setLayout(basepanelLayout);
        basepanelLayout.setHorizontalGroup(
            basepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basepanelLayout.createSequentialGroup()
                .addComponent(rail_transit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 510, Short.MAX_VALUE)
                .addComponent(button_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_logout)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        basepanelLayout.setVerticalGroup(
            basepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rail_transit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_logoutActionPerformed
        this.hide();
        global.lgn.setVisible(true);
    }//GEN-LAST:event_button_logoutActionPerformed

    private void button_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_backActionPerformed
        booktkt book=new booktkt();
        this.hide();
        book.setVisible(true);
    }//GEN-LAST:event_button_backActionPerformed

    private void table_trainsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_trainsMouseClicked
        int row=table_trains.getSelectedRow();
        Object tnoobj=table_trains.getValueAt(row, 0);
        int tno=(int) tnoobj;
        train cur=global.bkdetails.traveldate.trnlink.first;
        while(cur!=null) {
            if(cur.number==tno) {
                global.bkdetails.slcttrain=cur;
                break;
            }
            cur=cur.next;
        }
        this.hide();
        bookpassenger bkpsgr=new bookpassenger();
        bkpsgr.setVisible(true);
    }//GEN-LAST:event_table_trainsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showtrains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showtrains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showtrains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showtrains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showtrains().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basepanel;
    private javax.swing.JButton button_back;
    private javax.swing.JButton button_logout;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rail_transit;
    private javax.swing.JTable table_trains;
    // End of variables declaration//GEN-END:variables
}
