/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package railway;

/**
 *
 * @author cletu
 */
public class ticketframe extends javax.swing.JFrame {

    /**
     * Creates new form ticketframe
     */
    public ticketframe() {
        initComponents();
    }
    public ticketframe(ticket obj) {
        initComponents();
        train_name.setText(obj.tname);
        src_station.setText(obj.source.name);
        dest_station.setText(obj.destination.name);
        departure.setText(obj.srctime+"hrs");
        date.setText(obj.date.dt);
        psgr_name.setText(obj.name);
        psgr_age.setText(obj.age+"");
        coach_type.setText(obj.coachtype);
        quota.setText(obj.quota);
        ticket_fare.setText("Rs. "+obj.price);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        label_deststation = new javax.swing.JLabel();
        label_departure = new javax.swing.JLabel();
        label_date = new javax.swing.JLabel();
        label_psgrname = new javax.swing.JLabel();
        label_psgrage = new javax.swing.JLabel();
        label_coachtype = new javax.swing.JLabel();
        label_quota = new javax.swing.JLabel();
        label_fare = new javax.swing.JLabel();
        train_name = new javax.swing.JLabel();
        label_srcstation = new javax.swing.JLabel();
        src_station = new javax.swing.JLabel();
        dest_station = new javax.swing.JLabel();
        departure = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        psgr_name = new javax.swing.JLabel();
        psgr_age = new javax.swing.JLabel();
        coach_type = new javax.swing.JLabel();
        quota = new javax.swing.JLabel();
        ticket_fare = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("RAIL TRANSIT");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        label_deststation.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_deststation.setText("Destination Station: ");

        label_departure.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_departure.setText("Departure: ");

        label_date.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_date.setText("Date: ");

        label_psgrname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_psgrname.setText("Name of Passenger: ");

        label_psgrage.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_psgrage.setText("Age: ");

        label_coachtype.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_coachtype.setText("Class: ");

        label_quota.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_quota.setText("Quota: ");

        label_fare.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_fare.setText("Fare: ");

        train_name.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N

        label_srcstation.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_srcstation.setText("Source Station: ");

        src_station.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        dest_station.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        departure.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        date.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        psgr_name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        psgr_age.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        coach_type.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        quota.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        ticket_fare.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(train_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_srcstation)
                            .addComponent(label_deststation)
                            .addComponent(label_departure)
                            .addComponent(label_date)
                            .addComponent(label_psgrname)
                            .addComponent(label_psgrage)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(label_quota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(label_coachtype, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(label_fare))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(src_station, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dest_station, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(departure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(psgr_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(psgr_age, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(coach_type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ticket_fare, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(train_name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_srcstation)
                            .addComponent(src_station))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_deststation)
                            .addComponent(dest_station))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_departure)
                            .addComponent(departure))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_date)
                            .addComponent(date))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_psgrname)
                            .addComponent(psgr_name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_psgrage))
                    .addComponent(psgr_age))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_coachtype)
                    .addComponent(coach_type))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_quota)
                    .addComponent(quota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_fare)
                    .addComponent(ticket_fare))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ticketframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ticketframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ticketframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ticketframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ticketframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel coach_type;
    private javax.swing.JLabel date;
    private javax.swing.JLabel departure;
    private javax.swing.JLabel dest_station;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_coachtype;
    private javax.swing.JLabel label_date;
    private javax.swing.JLabel label_departure;
    private javax.swing.JLabel label_deststation;
    private javax.swing.JLabel label_fare;
    private javax.swing.JLabel label_psgrage;
    private javax.swing.JLabel label_psgrname;
    private javax.swing.JLabel label_quota;
    private javax.swing.JLabel label_srcstation;
    private javax.swing.JLabel psgr_age;
    private javax.swing.JLabel psgr_name;
    private javax.swing.JLabel quota;
    private javax.swing.JLabel src_station;
    private javax.swing.JLabel ticket_fare;
    private javax.swing.JLabel train_name;
    // End of variables declaration//GEN-END:variables
}
